name: Build audioDebugger

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-arch:
    name: Build (Arch Linux)
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
    - name: Checkout latest
      uses: actions/checkout@v4
      
    - name: Installing dependencies
      run: pacman -Syu --noconfirm alsa-lib fftw fmt glfw glib2 libportal lua protobuf

    - name: mkdir build
      run: mkdir build
      
    - name: make
      run: make
